services:
  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: yes
  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_INTERNAL://0.0.0.0:29092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  pub:
    build:
      context: ./pub
      dockerfile: Dockerfile
    container_name: publisher
    ports:
      - "8000:8000"
    depends_on:
      - kafka
    environment:
    - KAFKA_BOOTSTRAP_SERVERS=kafka:29092

  sub:
    build:
      context: ./sub
      dockerfile: Dockerfile
    container_name: subscriber
    ports:
      - "8001:8001"
    depends_on:
      - kafka
    environment:
    - KAFKA_BOOTSTRAP_SERVERS=kafka:29092

networks:
  default:
    name: kafka-network
